repos:
  - repo: https://github.com/dmytro-kucherenko/smartner-utils-package
    rev: ef457a5
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: go-fmt
      - id: go-imports
      - id: go-types
        name: Go types
        language: golang
        entry: go vet ./...
        files: \.go$