name: Pull Request Checks

on:
  pull_request:
    branches:
      - '**'

  push:
    branches:
      - 'main'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23.2

      - name: Run go vet
        run: go vet ./...

      - name: Run go mod tidy
        run: go mod tidy

      - name: Check for go.mod changes
        run: git diff --exit-code go.mod go.sum
