name: Pull Request Checks

on:
  pull_request:
    branches:
      - '**'

  push:
    branches:
      - 'main'

jobs:
  Linting:
    runs-on: ubuntu-latest
    steps:
      - name: Set up actions
        uses: actions/checkout@v4

      - name: Set up SDK
        uses: actions/setup-go@v4
        with:
          go-version: 1.23.2

      - name: Download packages
        run: go mod download

      - name: Check types
        run: go vet ./...

      - name: Check packages
        run: go mod tidy && git diff --exit-code go.mod go.sum
